config/routes.rb
ImagineCo::Application.routes.draw do
  
  # Admin Paths
  # match "admin-login" => "admin_sessions#check_session", :as => :login
  # match "admin-logout" => "admin_sessions#destroy", :as => :logout
  # match "admin-dashboard" => "admins#show", :as => :admin_dashboard
  
  # Teacher Login
  match "teacher-login" => "teacher_sessions#new", :as => :teacher_login
  match "teacher-logout" => "teacher_sessions#destroy", :as => :teacher_logout
  match "teacher-dashboard" => "accounts#show", :as => :teacher_dashboard
  
  # Student Login
  match "student-login" => "student_sessions#new", :as => :student_login
  match "student-logout" => "student_sessions#destroy", :as => :student_logout
  match "student-dashboard" => "students#show", :as => :student_dashboard
  
  # Ajax Routes
  match "assign-curriculum" => "ajax#assign_curriculum", :as => :assign_curriculum
  
  # Base Routes
  match "home" => "pages#index", :as => :home
  # match "about" => "pages#about", :as => :about
  
  resources :students
  resources :student_sessions
  resources :teacher_sessions
  resources :teachers
  resources :admins
  resources :admin_sessions
  resources :answers
  resources :questions
  resources :lessons
  resources :lesson_templates
  resources :accounts
  resources :classrooms
  resources :classroom_lessons
  resources :curriculums
  resources :lesson_results
  resources :courses
  
  root :to => "pages#index"
  
end

app/models/lesson.rb
# == Schema Information
#
# Table name: lessons
#
#  id                 :integer(4)      not null, primary key
#  lesson_template_id :integer(4)
#  student_id         :integer(4)
#  video_watched      :boolean(1)
#  complete           :boolean(1)
#  score              :text
#  created_at         :datetime
#  updated_at         :datetime
#

class Lesson < ActiveRecord::Base
  
  # Validations
  validates_presence_of :lesson_template_id, :on => :create, :message => "can't be blank"
  validates_presence_of :student_id, :on => :create, :message => "can't be blank"
  
  # Associations
  belongs_to :lesson_template
  belongs_to :student
  has_many :lesson_results
  
  # Scopes
  scope :test_complete, where(:complete => true)
  
  # Methods
  
  def name
    return self.lesson_template.name
  end
  
  def subject
    return self.lesson_template.subject
  end
  
  def questions
    return self.lesson_template.questions
  end
  
  def template_questions(lesson_template = nil)
    if lesson_template
      return lesson_template.questions.shuffle
    else
      return self.lesson_template.questions.shuffle
    end
  end
  
  def video_url
    return self.lesson_template.videos.last.video.url
  end
  
  def template_name
    return self.lesson_template.name
  end
  
  def test_complete?
    if self.complete == true
      return true
    else
      return false
    end
  end
  
  def amount_correct
    lesson_questions = self.template_questions(self.lesson_template)
    correct_answers = 0
    results = self.lesson_results
    results.each do |r|
      if Question.exists?(r.question_id)
        question = Question.find(r.question_id)
        case question.question_type
        when "Short_Answer"
          correct_answers += question.check_short_answer(r.student_answer)
        when "Essay"
          correct_answers += question.check_essay(r.student_answer)
        else
          correct_answers += question.check_multiple_choice(r.student_answer)
        end
      end
    end
    return "#{correct_answers}/#{lesson_questions.size}"
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  
   before_filter :require_teacher, :except => [:edit, :update]
   
   layout 'internal'
  # GET /lessons
  # GET /lessons.xml
  def index
    
    if params[:student_id]
      @student = Student.find(params[:student_id]);
    else
      @lessons = Lesson.all
    end
    
    if params[:classroom_id]
      @classroom = Classroom.find(params[:classroom_id])
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @lessons }
    end
  end

  # GET /lessons/1
  # GET /lessons/1.xml
  def show
    @lesson = Lesson.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @lesson }
    end
  end

  # GET /lessons/new
  # GET /lessons/new.xml
  def new
    if params[:student_id]
      @student = Student.find(params[:student_id])
    end
    
    if params[:classroom_id]
      @classroom_id = params[:classroom_id]
    end
    
    @lesson = Lesson.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @lesson }
    end
  end

  # GET /lessons/1/edit
  def edit
    @lesson = Lesson.find(params[:id])
  end

  # POST /lessons
  # POST /lessons.xml
  def create
    
    if params[:classroom_id]
      @classroom = Classroom.find(params[:classroom_id])
      @classroom.assign_lesson_to_students(params[:lesson][:lesson_template_id])
      classroom_check = false
    else
      @lesson = Lesson.new(params[:lesson])
      classroom_check = true
    end

    respond_to do |format|
      if classroom_check
        @lesson.save
        AppMailer.new_lesson_notification(params[:lesson][:student_id]).deliver
        format.html { redirect_to(students_path, :notice => 'Lesson was successfully assigned.') }
      elsif @classroom
        format.html { redirect_to(classroom_path(@classroom), :notice => 'Lesson assigned to classroom students.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /lessons/1
  # PUT /lessons/1.xml
  def update
    @lesson = Lesson.find(params[:id])
    
    score = Question.score_answers(params)
    video_watched = true
    complete = true
    
    respond_to do |format|
      if @lesson.update_attributes(:score => score, :video_watched => video_watched, :complete => complete )
        LessonResult.file_answers(params, @lesson)
        format.html { redirect_to(student_dashboard_path, :notice => 'Lesson was successfully completed.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @lesson.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.xml
  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy

    respond_to do |format|
      format.html { redirect_to(lessons_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<%= form_for @lesson do |f| %>
  <%= render :partial => 'layouts/error_block', :locals => {:obj => @lesson} %>
  <% if @student %>
    <%= f.hidden_field :student_id, :value => @student.id %>
  <% end %>
  <% if @classroom_id %>
    <%= hidden_field_tag :classroom_id, @classroom_id %>
  <% end %>
  <div class="field">
    <%= f.label :lesson_template_id, "Choose Lesson" %><br />
    <%= f.collection_select(:lesson_template_id, current_teacher.lesson_templates, :id, :name, {:prompt => "Choose Lesson"}) %>
  </div>
  <% unless @student || @classroom_id %>
    <div class="field">
      <%= f.label :student_id %><br />
      <%= f.collection_select(:student_id, current_teacher.students, :id, :full_name, {:prompt => "Select A Student"}) %>
    </div>
  <% end %>
  <div class="field">
    <%= f.submit "Assign Lesson", :class => 'button blue_button' %>
  </div>
<% end %>

app/views/lessons/_listed_lesson.html.erb
<li class="listed_student round">
  <div class="student_info student_panel">
    <div class="students_name">
      <%#= link_to lesson.name, lesson, :class => "view_lesson" %> 
      <h3 class="view_lesson"><%= lesson.name %></h3>
    </div>
    <ul class="student_creds">
      <li>Lesson Score: <%= link_to "#{lesson.score}", lesson_result_path(lesson), :class => "score_trigger" %></li>
      <li>Lesson Date: <%= (lesson.updated_at).to_s(:pretty) %></li>
    </ul>
  </div>
  <div class="student_actions">
  </div>
  <div class="test_view round">

  </div>
  <div class="clear"></div>
</li>

app/views/lessons/_test_template.html.erb
<div id="lesson_form">
  <%= form_for(lesson, :class => "round") do |f| %>
    <%= render :partial => 'layouts/error_block', :locals => {:obj => lesson} %>
    <div id="slider">
     <div class="scroll">
       <div class="scroll_container">
          <% lesson.questions.each_with_index do |q,i| %>
            <% if q.question_type == "Multiple_Choice" %>
              <%= render :partial => 'questions/multi_choice', :locals => {:i => i, :q => q} %>
            <% elsif q.question_type == "Short_Answer" %>
              <%= render :partial => 'questions/short_answer', :locals => {:i => i, :q => q} %>
            <% else q.question_type == "Essay" %>
              <%= render :partial => 'questions/essay', :locals => {:i => i, :q => q} %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div id="slider_nav">
      <ul class="navigation">
        <% lesson.questions.each_with_index do |q,i| %>
          <li><%= link_to "", "#panel#{i + 1}", :class => "nav_links" %></li>
        <% end %>
      </ul>
    </div>
    <div id="buttonBar" class="submit">
      <%= f.submit "Submit Test", :class => "button green_button" %>
      <div id="question_counter">
        Question: <span id="count">1</span> / <span id="total"><%= lesson.questions.size %></span>
      </div>
    </div>
  <% end %>
</div>

app/views/lessons/edit.html.erb
<% content_for :page_actions do %>
  <div id="launch_button">
    <%= link_to 'Back to Dashboard', student_dashboard_path, :class => "button blue_button" %>
  </div>
<% end %>

<div class="content_segment top_hr">
  <h2 class="user_name"><%= (current_student.full_name).titleize %></h2>
  <div class="clear"></div>

  <h3></h3>
  <div id="student_lessons" class="round">
    <div id="player"></div>
    <%= render :partial => 'lessons/test_template', :locals => {:lesson => @lesson} %>
  </div>
</div>

<% content_for :overlays do %>

<% end %>

<% content_for :javascripts do %>
  <script type="text/javascript" charset="utf-8">
    jQuery(document).ready(function() {
      test.initTest();
      validate.testQuestions();
    });
  </script>
<% end %>

app/views/lessons/index.html.erb
<% content_for :page_actions do %>
   <div id="launch_button">
     <%#= link_to 'Add Students', new_classroom_path, :id => "add_student", :class => "button green_button add add_form" %>
   </div>
<% end %>

<div class="content_segment top_hr">
  <h2 class="user_name"><%= (current_teacher.full_name).titleize %> - <%= link_to(@classroom.name, @classroom) if @classroom %></h2>
  <div class="clear"></div>

  <h3>Lessons - <%= (@student.full_name).titleize if @student %></h3>
  <div id="student_lessons" class="round">
    <ul id="student_list">
      <% @student.lessons.each do |lesson| %>
        <%= render :partial => 'lessons/listed_lesson', :locals => {:lesson => lesson} %>
      <% end %>
    </ul>
  </div>

</div>

<% content_for :overlays do %>

<% end %>

<% content_for :javascripts do %>
  <script type="text/javascript" charset="utf-8">
    jQuery(document).ready(function() {
      triggers.loadLessonPanel();
    });
  </script>
<% end %>

app/views/lessons/new.html.erb
<div class="full_row">
  <h2 class="page_header">Assign Lesson <%= "to #{@student.full_name}" if @student %></h2>
  <div class="column_2">
    <%= render :partial => 'lessons/form' %>
  </div>
</div>

app/views/lessons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Lesson template:</b>
  <%= @lesson.lesson_template_id %>
</p>

<p>
  <b>User:</b>
  <%= @lesson.user_id %>
</p>

<p>
  <b>Video watched:</b>
  <%= @lesson.video_watched %>
</p>

<p>
  <b>Complete:</b>
  <%= @lesson.complete %>
</p>

<p>
  <b>Score:</b>
  <%= @lesson.score %>
</p>


<%= link_to 'Edit', edit_lesson_path(@lesson) %> |
<%= link_to 'Back', lessons_path %>