config/routes.rb
ImagineCo::Application.routes.draw do
  
  # Admin Paths
  # match "admin-login" => "admin_sessions#check_session", :as => :login
  # match "admin-logout" => "admin_sessions#destroy", :as => :logout
  # match "admin-dashboard" => "admins#show", :as => :admin_dashboard
  
  # Teacher Login
  match "teacher-login" => "teacher_sessions#new", :as => :teacher_login
  match "teacher-logout" => "teacher_sessions#destroy", :as => :teacher_logout
  match "teacher-dashboard" => "accounts#show", :as => :teacher_dashboard
  
  # Student Login
  match "student-login" => "student_sessions#new", :as => :student_login
  match "student-logout" => "student_sessions#destroy", :as => :student_logout
  match "student-dashboard" => "students#show", :as => :student_dashboard
  
  # Ajax Routes
  match "assign-curriculum" => "ajax#assign_curriculum", :as => :assign_curriculum
  
  # Base Routes
  match "home" => "pages#index", :as => :home
  # match "about" => "pages#about", :as => :about
  
  resources :students
  resources :student_sessions
  resources :teacher_sessions
  resources :teachers
  resources :admins
  resources :admin_sessions
  resources :answers
  resources :questions
  resources :lessons
  resources :lesson_templates
  resources :accounts
  resources :classrooms
  resources :classroom_lessons
  resources :curriculums
  resources :lesson_results
  resources :courses
  
  root :to => "pages#index"
  
end

app/models/teacher.rb
# == Schema Information
#
# Table name: teachers
#
#  id                  :integer(4)      not null, primary key
#  first_name          :string(255)
#  last_name           :string(255)
#  email               :string(255)
#  username            :string(255)
#  crypted_password    :string(255)
#  password_salt       :string(255)
#  persistence_token   :string(255)
#  single_access_token :string(255)
#  perishable_token    :string(255)
#  login_count         :integer(4)
#  failed_login_count  :integer(4)
#  last_request_at     :datetime
#  current_login_at    :datetime
#  last_login_at       :datetime
#  current_login_ip    :string(255)
#  last_login_ip       :string(255)
#  created_at          :datetime
#  updated_at          :datetime
#  admin               :boolean(1)
#  account_id          :integer(4)
#

class Teacher < ActiveRecord::Base
  
  #Associations
  belongs_to :account
  has_many :classrooms
  has_many :curriculums
  has_many :lesson_templates, :through => :curriculums
  
  validates_presence_of :first_name, :on => :create, :message => "can't be blank"
  validates_presence_of :last_name, :on => :create, :message => "can't be blank"
  validates_uniqueness_of :email, :on => :create, :message => "must be unique"
  
  #Authlogic
  acts_as_authentic do |c|
    c.login_field = :email
    c.logged_in_timeout = 120.minutes
  end
  
  # Scopes
  scope :admin_rights, where("admin = ?", true)
  scope :account_teachers, lambda { |account_id| where("account_id = ?", account_id) }
  
  # Methods
  
  def self.setup_new_teacher(params, account)    

  end
  
  def full_name
    fullname = self.first_name + " " + self.last_name
    return fullname
  end
  
  def students
    unless self.classrooms.blank?
      students = Array.new
      self.classrooms.each do |classroom| 
        students.push(classroom.students)
      end
      flatten_students = students.flatten!
      compacted_students = flatten_students.compact
      return compacted_students
    end
  end
  
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  
  before_filter :require_teacher
  
  layout 'internal'
  
  def index
    @teachers = Teacher.account_teachers(current_teacher.account.id)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @teachers }
    end
  end

  def show
    @teacher = Teacher.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @teacher }
    end
  end

  def new
    @teacher = Teacher.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @teacher }
    end
  end

  def edit
    @teacher = Teacher.find(params[:id])
  end

  def create
    @teacher = Teacher.new(params[:teacher])
    @teacher.account_id = current_teacher.account.id
    respond_to do |format|
      if @teacher.save_without_session_maintenance
        format.html { redirect_to teachers_path, :notice => 'Teacher was successfully created.' }
        format.xml  { render :xml => @teacher, :status => :created, :location => @teacher }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @teacher.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @teacher = Teacher.find(params[:id])

    respond_to do |format|
      if @teacher.update_attributes(params[:teacher])
        format.html { redirect_to(@teacher, :notice => 'Teacher was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @teacher.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @teacher = Teacher.find(params[:id])
    @teacher.destroy

    respond_to do |format|
      format.html { redirect_to(teachers_url) }
      format.xml  { head :ok }
    end
  end
  
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_dashboard_nav.html.erb
<div class="dashboard_nav">
  <ul>
  <% if current_teacher.admin? %>
    <li>
      <%= link_to "Add Teacher", new_teacher_path%>
    </li>
  <% end %>
    <li>
      <%= link_to "Add Student", new_student_path %>
    </li>
    <li>
      <%= link_to "Add Test", new_lesson_template_path %>
    </li>
</div>

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <%= render :partial => "layouts/error_block", :locals => {:obj => @teacher} %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Retype Password" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field checkbox stacked">
    <%= f.check_box :admin %><%= f.label :admin %>
  </div>
  <div class="field">
    <%= f.submit button_text, :class => 'button blue_button' %>
  </div>
<% end %>

app/views/teachers/_listed_teacher.html.erb
<li class="listed_student round">
   <div class="student_info student_panel">
     <div class="students_name">
      <%= link_to teacher.full_name, teacher_path(teacher), :class => "view_teacher" %> 
      <%= button_to "Delete Teacher", teacher, :method => 'delete', :confirm => 'Are you sure you want to delete this student?', :title => "Delete Student", :class => "remove_button red" if current_teacher.admin %></div>
     <ul class="student_creds">
       <li>Login: <%= teacher.username %></li>
       <li>Last Login: <%= (teacher.last_login_at).to_s(:pretty) unless teacher.last_login_at.blank?  %></li>
     </ul>
   </div>
   <div class="clear"></div>
 </li>

app/views/teachers/dashboard.html.erb
<h2 class="dashboard">Welcome <%= (current_teacher.full_name).titleize %></h2>

<%= render :partial => 'dashboard_nav' %>

app/views/teachers/edit.html.erb
<h1>Editing teacher</h1>

<%= render 'form' %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<% content_for :page_actions do %>
  <% if current_teacher.admin %>
   <div id="launch_button">
     <%= link_to 'Add New Teacher', new_teacher_path, :id => "add_teacher", :class => "button green_button add add_form" %>
   </div>
  <% end %>
<% end %>

<div class="content_segment top_hr">
  <h2 class="user_name"><%= (current_teacher.full_name).titleize %></h2>
  <div class="clear"></div>

  <h3>Account Teachers</h3>
  <div id="student_lessons" class="round">
    <ul id="student_list">
      <% @teachers.each do |teacher| %>
        <%= render :partial => 'teachers/listed_teacher', :locals => {:teacher => teacher} unless teacher.id == current_teacher.id %>
      <% end %>
    </ul>
  </div>

</div>

<% content_for :overlays do %>

<% end %>

<% content_for :javascripts do %>
  <script type="text/javascript" charset="utf-8">
    jQuery(document).ready(function() {
      
    });
  </script>
<% end %>

app/views/teachers/new.html.erb
<div class="full_row">
  <div class="column sign_up_form">
    <div id="form_panel" class="box round light_panel">
      <h2 class="panel_title blue_title">Add Teacher to Account</h2>
      <%= render :partial => 'teachers/form', :locals => {:button_text => "Create Teacher"}%>
    </div>
  </div>
</div>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @teacher.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @teacher.last_name %>
</p>

<p>
  <b>Email:</b>
  <%= @teacher.email %>
</p>

<p>
  <b>Password:</b>
  <%= @teacher.password %>
</p>


<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>